name: Jekyll GH-Pages Tagging Action
description: Provides a fully-automated solution for Jekyll tag management that is 100% compatible with GitHub Pages by working through GitHub Actions instead of a plugin.
author: 'ragdata'
inputs:
    posts_dir:
        description: "Path to '_posts' directory from root"
        required: true
        default: "_posts"
    tags_dir:
        description: "Path to '_tags' directory from root"
        required: true
        default: "_tags"
    tags_layout:
        description: "Layout used by tag files"
        required: true
        default: "tags"
    feeds_dir:
        description: "Path to '_feeds' directory from root"
        required: false
        default: "_feeds"
    feeds_layout:
        description: "Layout used by feed files"
        required: false
        default: "feed"
    token:
        description: "PAT token identifying user"
        required: true


runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.token }}
        - ${{ inputs.posts_dir }}
        - ${{ inputs.tags_dir }}
        - ${{ inputs.tags_layout }}
        - ${{ inputs.feeds_dir }}
        - ${{ inputs.feeds_layout }}

branding:
    icon: 'tag'
    color: 'red'
